<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Carbon\Carbon;


class ImagesSeeder extends Seeder
{
    public function run(): void
    {
        $image_path = [
            'http://localhost:8000/storage/game_images/undertale/undertale_0.jpg',
            'http://localhost:8000/storage/game_images/undertale/undertale_1.jpg',
            'http://localhost:8000/storage/game_images/undertale/undertale_2.jpg',
            'http://localhost:8000/storage/game_images/undertale/undertale_3.jpg',
            'http://localhost:8000/storage/game_images/undertale/undertale_4.jpg',
            'http://localhost:8000/storage/game_images/uncharted_the_legacy_collection/uncharted_the_legacy_collection_0.jpg',
            'http://localhost:8000/storage/game_images/uncharted_the_legacy_collection/uncharted_the_legacy_collection_1.jpg',
            'http://localhost:8000/storage/game_images/uncharted_the_legacy_collection/uncharted_the_legacy_collection_2.jpg',
            'http://localhost:8000/storage/game_images/uncharted_the_legacy_collection/uncharted_the_legacy_collection_3.jpg',
            'http://localhost:8000/storage/game_images/uncharted_the_legacy_collection/uncharted_the_legacy_collection_4.jpg',
            'http://localhost:8000/storage/game_images/hitman_3/hitman_3_0.jpg',
            'http://localhost:8000/storage/game_images/hitman_3/hitman_3_1.jpg',
            'http://localhost:8000/storage/game_images/hitman_3/hitman_3_2.jpg',
            'http://localhost:8000/storage/game_images/hitman_3/hitman_3_3.jpg',
            'http://localhost:8000/storage/game_images/hitman_3/hitman_3_4.jpg',
            'http://localhost:8000/storage/game_images/tetris_effect_connected/tetris_effect_connected_0.jpg',
            'http://localhost:8000/storage/game_images/tetris_effect_connected/tetris_effect_connected_1.jpg',
            'http://localhost:8000/storage/game_images/tetris_effect_connected/tetris_effect_connected_2.jpg',
            'http://localhost:8000/storage/game_images/tetris_effect_connected/tetris_effect_connected_3.jpg',
            'http://localhost:8000/storage/game_images/tetris_effect_connected/tetris_effect_connected_4.jpg',
            'http://localhost:8000/storage/game_images/terraria/terraria_0.jpg',
            'http://localhost:8000/storage/game_images/terraria/terraria_1.jpg',
            'http://localhost:8000/storage/game_images/terraria/terraria_2.jpg',
            'http://localhost:8000/storage/game_images/terraria/terraria_3.jpg',
            'http://localhost:8000/storage/game_images/terraria/terraria_4.jpg',
            'http://localhost:8000/storage/game_images/fortnite/fortnite_0.jpg',
            'http://localhost:8000/storage/game_images/fortnite/fortnite_1.jpg',
            'http://localhost:8000/storage/game_images/fortnite/fortnite_2.jpg',
            'http://localhost:8000/storage/game_images/fortnite/fortnite_3.jpg',
            'http://localhost:8000/storage/game_images/fortnite/fortnite_4.jpg',
            'http://localhost:8000/storage/game_images/call_of_duty_2_black_ops_2/call_of_duty_2_black_ops_2_0.jpg',
            'http://localhost:8000/storage/game_images/call_of_duty_2_black_ops_2/call_of_duty_2_black_ops_2_1.jpg',
            'http://localhost:8000/storage/game_images/call_of_duty_2_black_ops_2/call_of_duty_2_black_ops_2_2.jpg',
            'http://localhost:8000/storage/game_images/call_of_duty_2_black_ops_2/call_of_duty_2_black_ops_2_3.jpg',
            'http://localhost:8000/storage/game_images/call_of_duty_2_black_ops_2/call_of_duty_2_black_ops_2_4.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_4/assassins_creed_4_0.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_4/assassins_creed_4_1.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_4/assassins_creed_4_2.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_4/assassins_creed_4_3.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_4/assassins_creed_4_4.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_v/grand_theft_auto_v_0.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_v/grand_theft_auto_v_1.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_v/grand_theft_auto_v_2.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_v/grand_theft_auto_v_3.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_v/grand_theft_auto_v_4.jpg',
            'http://localhost:8000/storage/game_images/halo_the_master_chief_collection/halo_the_master_chief_collection_0.jpg',
            'http://localhost:8000/storage/game_images/halo_the_master_chief_collection/halo_the_master_chief_collection_1.jpg',
            'http://localhost:8000/storage/game_images/halo_the_master_chief_collection/halo_the_master_chief_collection_2.jpg',
            'http://localhost:8000/storage/game_images/halo_the_master_chief_collection/halo_the_master_chief_collection_3.jpg',
            'http://localhost:8000/storage/game_images/halo_the_master_chief_collection/halo_the_master_chief_collection_4.jpg',
            'http://localhost:8000/storage/game_images/final_fantasy_7_remake_intergrade/final_fantasy_7_remake_intergrade_0.jpg',
            'http://localhost:8000/storage/game_images/final_fantasy_7_remake_intergrade/final_fantasy_7_remake_intergrade_1.jpg',
            'http://localhost:8000/storage/game_images/final_fantasy_7_remake_intergrade/final_fantasy_7_remake_intergrade_2.jpg',
            'http://localhost:8000/storage/game_images/final_fantasy_7_remake_intergrade/final_fantasy_7_remake_intergrade_3.jpg',
            'http://localhost:8000/storage/game_images/final_fantasy_7_remake_intergrade/final_fantasy_7_remake_intergrade_4.jpg',
            'http://localhost:8000/storage/game_images/minecraft/minecraft_0.jpg',
            'http://localhost:8000/storage/game_images/minecraft/minecraft_1.jpg',
            'http://localhost:8000/storage/game_images/minecraft/minecraft_2.jpg',
            'http://localhost:8000/storage/game_images/minecraft/minecraft_3.jpg',
            'http://localhost:8000/storage/game_images/minecraft/minecraft_4.jpg',
            'http://localhost:8000/storage/game_images/overwatch_2/overwatch_2_0.jpg',
            'http://localhost:8000/storage/game_images/overwatch_2/overwatch_2_1.jpg',
            'http://localhost:8000/storage/game_images/overwatch_2/overwatch_2_2.jpg',
            'http://localhost:8000/storage/game_images/overwatch_2/overwatch_2_3.jpg',
            'http://localhost:8000/storage/game_images/overwatch_2/overwatch_2_4.jpg',
            'http://localhost:8000/storage/game_images/ea_sports_fc_24/ea_sports_fc_24_0.jpg',
            'http://localhost:8000/storage/game_images/ea_sports_fc_24/ea_sports_fc_24_1.jpg',
            'http://localhost:8000/storage/game_images/ea_sports_fc_24/ea_sports_fc_24_2.jpg',
            'http://localhost:8000/storage/game_images/ea_sports_fc_24/ea_sports_fc_24_3.jpg',
            'http://localhost:8000/storage/game_images/ea_sports_fc_24/ea_sports_fc_24_4.jpg',
            'http://localhost:8000/storage/game_images/pc_building_simulator/pc_building_simulator_0.jpg',
            'http://localhost:8000/storage/game_images/pc_building_simulator/pc_building_simulator_1.jpg',
            'http://localhost:8000/storage/game_images/pc_building_simulator/pc_building_simulator_2.jpg',
            'http://localhost:8000/storage/game_images/pc_building_simulator/pc_building_simulator_3.jpg',
            'http://localhost:8000/storage/game_images/pc_building_simulator/pc_building_simulator_4.jpg',
            'http://localhost:8000/storage/game_images/persona_5_royal/persona_5_royal_0.jpg',
            'http://localhost:8000/storage/game_images/persona_5_royal/persona_5_royal_1.jpg',
            'http://localhost:8000/storage/game_images/persona_5_royal/persona_5_royal_2.jpg',
            'http://localhost:8000/storage/game_images/persona_5_royal/persona_5_royal_3.jpg',
            'http://localhost:8000/storage/game_images/persona_5_royal/persona_5_royal_4.jpg',
            'http://localhost:8000/storage/game_images/steam_deck/steam_deck_0.jpg',
            'http://localhost:8000/storage/game_images/steam_deck/steam_deck_1.jpg',
            'http://localhost:8000/storage/game_images/steam_deck/steam_deck_2.jpg',
            'http://localhost:8000/storage/game_images/steam_deck/steam_deck_3.jpg',
            'http://localhost:8000/storage/game_images/steam_deck/steam_deck_4.jpg',
            'http://localhost:8000/storage/game_images/rocket_league/rocket_league_0.jpg',
            'http://localhost:8000/storage/game_images/rocket_league/rocket_league_1.jpg',
            'http://localhost:8000/storage/game_images/rocket_league/rocket_league_2.jpg',
            'http://localhost:8000/storage/game_images/rocket_league/rocket_league_3.jpg',
            'http://localhost:8000/storage/game_images/rocket_league/rocket_league_4.jpg',
            'http://localhost:8000/storage/game_images/counter_strike_2/counter_strike_2_0.jpg',
            'http://localhost:8000/storage/game_images/counter_strike_2/counter_strike_2_1.jpg',
            'http://localhost:8000/storage/game_images/counter_strike_2/counter_strike_2_2.jpg',
            'http://localhost:8000/storage/game_images/counter_strike_2/counter_strike_2_3.jpg',
            'http://localhost:8000/storage/game_images/counter_strike_2/counter_strike_2_4.jpg',
            'http://localhost:8000/storage/game_images/forza_horizon_5/forza_horizon_5_0.jpg',
            'http://localhost:8000/storage/game_images/forza_horizon_5/forza_horizon_5_1.jpg',
            'http://localhost:8000/storage/game_images/forza_horizon_5/forza_horizon_5_2.jpg',
            'http://localhost:8000/storage/game_images/forza_horizon_5/forza_horizon_5_3.jpg',
            'http://localhost:8000/storage/game_images/forza_horizon_5/forza_horizon_5_4.jpg',
            'http://localhost:8000/storage/game_images/left_4_dead_2/left_4_dead_2_0.jpg',
            'http://localhost:8000/storage/game_images/left_4_dead_2/left_4_dead_2_1.jpg',
            'http://localhost:8000/storage/game_images/left_4_dead_2/left_4_dead_2_2.jpg',
            'http://localhost:8000/storage/game_images/left_4_dead_2/left_4_dead_2_3.jpg',
            'http://localhost:8000/storage/game_images/left_4_dead_2/left_4_dead_2_4.jpg',
            'http://localhost:8000/storage/game_images/hitman_3_seven_deadly_sins_collection/hitman_3_seven_deadly_sins_collection_0.jpg',
            'http://localhost:8000/storage/game_images/hitman_3_seven_deadly_sins_collection/hitman_3_seven_deadly_sins_collection_1.jpg',
            'http://localhost:8000/storage/game_images/hitman_3_seven_deadly_sins_collection/hitman_3_seven_deadly_sins_collection_2.jpg',
            'http://localhost:8000/storage/game_images/hitman_3_seven_deadly_sins_collection/hitman_3_seven_deadly_sins_collection_3.jpg',
            'http://localhost:8000/storage/game_images/hitman_3_seven_deadly_sins_collection/hitman_3_seven_deadly_sins_collection_4.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_vi/grand_theft_auto_vi_0.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_vi/grand_theft_auto_vi_1.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_vi/grand_theft_auto_vi_2.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_vi/grand_theft_auto_vi_3.jpg',
            'http://localhost:8000/storage/game_images/grand_theft_auto_vi/grand_theft_auto_vi_4.jpg',
            'http://localhost:8000/storage/game_images/resident_evil_4/resident_evil_4_0.jpg',
            'http://localhost:8000/storage/game_images/resident_evil_4/resident_evil_4_1.jpg',
            'http://localhost:8000/storage/game_images/resident_evil_4/resident_evil_4_2.jpg',
            'http://localhost:8000/storage/game_images/resident_evil_4/resident_evil_4_3.jpg',
            'http://localhost:8000/storage/game_images/resident_evil_4/resident_evil_4_4.jpg',
            'http://localhost:8000/storage/game_images/mortal_kombat_1/mortal_kombat_1_0.jpg',
            'http://localhost:8000/storage/game_images/mortal_kombat_1/mortal_kombat_1_1.jpg',
            'http://localhost:8000/storage/game_images/mortal_kombat_1/mortal_kombat_1_2.jpg',
            'http://localhost:8000/storage/game_images/mortal_kombat_1/mortal_kombat_1_3.jpg',
            'http://localhost:8000/storage/game_images/mortal_kombat_1/mortal_kombat_1_4.jpg',
            'http://localhost:8000/storage/game_images/red_dead_redemption_2/red_dead_redemption_2_0.jpg',
            'http://localhost:8000/storage/game_images/red_dead_redemption_2/red_dead_redemption_2_1.jpg',
            'http://localhost:8000/storage/game_images/red_dead_redemption_2/red_dead_redemption_2_2.jpg',
            'http://localhost:8000/storage/game_images/red_dead_redemption_2/red_dead_redemption_2_3.jpg',
            'http://localhost:8000/storage/game_images/red_dead_redemption_2/red_dead_redemption_2_4.jpg',
            'http://localhost:8000/storage/game_images/god_of_war/god_of_war_0.jpg',
            'http://localhost:8000/storage/game_images/god_of_war/god_of_war_1.jpg',
            'http://localhost:8000/storage/game_images/god_of_war/god_of_war_2.jpg',
            'http://localhost:8000/storage/game_images/god_of_war/god_of_war_3.jpg',
            'http://localhost:8000/storage/game_images/god_of_war/god_of_war_4.jpg',
            'http://localhost:8000/storage/game_images/tom_clancys_rainbow_six_siege/tom_clancys_rainbow_six_siege_0.jpg',
            'http://localhost:8000/storage/game_images/tom_clancys_rainbow_six_siege/tom_clancys_rainbow_six_siege_1.jpg',
            'http://localhost:8000/storage/game_images/tom_clancys_rainbow_six_siege/tom_clancys_rainbow_six_siege_2.jpg',
            'http://localhost:8000/storage/game_images/tom_clancys_rainbow_six_siege/tom_clancys_rainbow_six_siege_3.jpg',
            'http://localhost:8000/storage/game_images/tom_clancys_rainbow_six_siege/tom_clancys_rainbow_six_siege_4.jpg',
            'http://localhost:8000/storage/game_images/dead_space/dead_space_0.jpg',
            'http://localhost:8000/storage/game_images/dead_space/dead_space_1.jpg',
            'http://localhost:8000/storage/game_images/dead_space/dead_space_2.jpg',
            'http://localhost:8000/storage/game_images/dead_space/dead_space_3.jpg',
            'http://localhost:8000/storage/game_images/dead_space/dead_space_4.jpg',
            'http://localhost:8000/storage/game_images/grounded/grounded_0.jpg',
            'http://localhost:8000/storage/game_images/grounded/grounded_1.jpg',
            'http://localhost:8000/storage/game_images/grounded/grounded_2.jpg',
            'http://localhost:8000/storage/game_images/grounded/grounded_3.jpg',
            'http://localhost:8000/storage/game_images/grounded/grounded_4.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077/cyberpunk_2077_0.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077/cyberpunk_2077_1.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077/cyberpunk_2077_2.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077/cyberpunk_2077_3.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077/cyberpunk_2077_4.jpg',
            'http://localhost:8000/storage/game_images/sea_of_thieves/sea_of_thieves_0.jpg',
            'http://localhost:8000/storage/game_images/sea_of_thieves/sea_of_thieves_1.jpg',
            'http://localhost:8000/storage/game_images/sea_of_thieves/sea_of_thieves_2.jpg',
            'http://localhost:8000/storage/game_images/sea_of_thieves/sea_of_thieves_3.jpg',
            'http://localhost:8000/storage/game_images/sea_of_thieves/sea_of_thieves_4.jpg',
            'http://localhost:8000/storage/game_images/sekiro_shadows_die_twice/sekiro_shadows_die_twice_0.jpg',
            'http://localhost:8000/storage/game_images/sekiro_shadows_die_twice/sekiro_shadows_die_twice_1.jpg',
            'http://localhost:8000/storage/game_images/sekiro_shadows_die_twice/sekiro_shadows_die_twice_2.jpg',
            'http://localhost:8000/storage/game_images/sekiro_shadows_die_twice/sekiro_shadows_die_twice_3.jpg',
            'http://localhost:8000/storage/game_images/sekiro_shadows_die_twice/sekiro_shadows_die_twice_4.jpg',
            'http://localhost:8000/storage/game_images/monster_hunter_rise/monster_hunter_rise_0.jpg',
            'http://localhost:8000/storage/game_images/monster_hunter_rise/monster_hunter_rise_1.jpg',
            'http://localhost:8000/storage/game_images/monster_hunter_rise/monster_hunter_rise_2.jpg',
            'http://localhost:8000/storage/game_images/monster_hunter_rise/monster_hunter_rise_3.jpg',
            'http://localhost:8000/storage/game_images/monster_hunter_rise/monster_hunter_rise_4.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_valhalla/assassins_creed_valhalla_0.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_valhalla/assassins_creed_valhalla_1.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_valhalla/assassins_creed_valhalla_2.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_valhalla/assassins_creed_valhalla_3.jpg',
            'http://localhost:8000/storage/game_images/assassins_creed_valhalla/assassins_creed_valhalla_4.jpg',
            'http://localhost:8000/storage/game_images/persona_3_reload/persona_3_reload_0.jpg',
            'http://localhost:8000/storage/game_images/persona_3_reload/persona_3_reload_1.jpg',
            'http://localhost:8000/storage/game_images/persona_3_reload/persona_3_reload_2.jpg',
            'http://localhost:8000/storage/game_images/persona_3_reload/persona_3_reload_3.jpg',
            'http://localhost:8000/storage/game_images/persona_3_reload/persona_3_reload_4.jpg',
            'http://localhost:8000/storage/game_images/horizon_forbidden_west/horizon_forbidden_west_0.jpg',
            'http://localhost:8000/storage/game_images/horizon_forbidden_west/horizon_forbidden_west_1.jpg',
            'http://localhost:8000/storage/game_images/horizon_forbidden_west/horizon_forbidden_west_2.jpg',
            'http://localhost:8000/storage/game_images/horizon_forbidden_west/horizon_forbidden_west_3.jpg',
            'http://localhost:8000/storage/game_images/horizon_forbidden_west/horizon_forbidden_west_4.jpg',
            'http://localhost:8000/storage/game_images/baldurs_gate_3/baldurs_gate_3_0.jpg',
            'http://localhost:8000/storage/game_images/baldurs_gate_3/baldurs_gate_3_1.jpg',
            'http://localhost:8000/storage/game_images/baldurs_gate_3/baldurs_gate_3_2.jpg',
            'http://localhost:8000/storage/game_images/baldurs_gate_3/baldurs_gate_3_3.jpg',
            'http://localhost:8000/storage/game_images/baldurs_gate_3/baldurs_gate_3_4.jpg',
            'http://localhost:8000/storage/game_images/elden_ring/elden_ring_0.jpg',
            'http://localhost:8000/storage/game_images/elden_ring/elden_ring_1.jpg',
            'http://localhost:8000/storage/game_images/elden_ring/elden_ring_2.jpg',
            'http://localhost:8000/storage/game_images/elden_ring/elden_ring_3.jpg',
            'http://localhost:8000/storage/game_images/elden_ring/elden_ring_4.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077_phantom_liberty/cyberpunk_2077_phantom_liberty_0.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077_phantom_liberty/cyberpunk_2077_phantom_liberty_1.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077_phantom_liberty/cyberpunk_2077_phantom_liberty_2.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077_phantom_liberty/cyberpunk_2077_phantom_liberty_3.jpg',
            'http://localhost:8000/storage/game_images/cyberpunk_2077_phantom_liberty/cyberpunk_2077_phantom_liberty_4.jpg',
            /*'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',
            'debug_purpose',*/
            //'http://localhost:8000/storage/game_images/',
            //'http://localhost:8000/storage/game_images/',
            //'http://localhost:8000/storage/game_images/',
            //'http://localhost:8000/storage/game_images/',
            //'http://localhost:8000/storage/game_images/',

        ];
        $const_img = 5;
        for($i=0;$i<sizeof($image_path)+1;$i++) //n$image_path cicli games_images + ($+1) users_images
        {
            if($i >= sizeof($image_path)){
                DB::table('images')->insert(['image_path' => 'http://localhost:8000/storage/user_images/Default.png',]);
                DB::table('images')->insert(['image_path' => 'http://localhost:8000/storage/achievement_images/default.png',]);
            }
            if($i < sizeof($image_path)){
                $j = floor(($i+$const_img) / $const_img);
                DB::table('images')->insert([
                    'image_path' => $image_path[$i],
                    'game_id' => $j,
                ]);
            }
        }





            /*
            else{
                //$j=$i/5;
                $j = floor($i / 5);
                DB::table('images')->insert([
                    //'game_id' => $j,//PLACEHOLDER RNG
                    //'user_id' => rand(1,19),
                    //'achievement_id' => rand(1,19),
                    //'image_path' => $image_path[$i]
                ]);
            }*/
        }
}

